import * as XLSX from "xlsx";

const EXCEL_HEADERS: (string | number)[] = [
  "Report ID",
  "Report Type",
  "Title",
  "Generated By",
  "Generated Date",
  "Status",
  "Category",
  "Total Records",
  "File Size",
  "Description",
];

const formatRowData = (row: any, filtered: boolean): (string | number)[] => {
  const data = filtered ? row.original : row;
  return [
    data.id,
    data.reportType,
    data.title,
    data.generatedBy,
    data.generatedDate,
    data.status,
    data.category,
    data.totalRecords,
    data.fileSize,
    data.description,
  ];
};

const ExportReportsDataToExcel = (filtered: string, data: any[]): void => {
  const dynamicData = [
    EXCEL_HEADERS,
    ...data.map((row) => formatRowData(row, filtered === "filtered")),
  ];

  const ws: XLSX.WorkSheet = XLSX.utils.aoa_to_sheet(dynamicData);

  // Set column widths
  const colWidths = [
    { wch: 15 }, // Report ID
    { wch: 20 }, // Report Type
    { wch: 30 }, // Title
    { wch: 20 }, // Generated By
    { wch: 15 }, // Generated Date
    { wch: 12 }, // Status
    { wch: 15 }, // Category
    { wch: 15 }, // Total Records
    { wch: 12 }, // File Size
    { wch: 40 }, // Description
  ];
  ws["!cols"] = colWidths;

  const wb: XLSX.WorkBook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Admin Reports");

  const fileName = `Admin_Reports_${
    new Date().toISOString().split("T")[0]
  }.xlsx`;
  XLSX.writeFile(wb, fileName, { bookSST: true });
};

export default ExportReportsDataToExcel;

