import * as XLSX from "xlsx";

const EXCEL_HEADERS: (string | number)[] = [
  "Report Type",
  "Title",
  "Description",
  "Generated By",
  "Generated Date",
  "Status",
  "Category",
  "Total Records",
  "File Size",
  "Download URL",
  "Expiry Date",
  "Updated At",
  "Created At",
];

const formatRowData = (row: any, filtered: boolean): (string | number)[] => {
  const data = filtered ? row.original : row;
  return [
    data.reportType,
    data.title,
    data.description,
    data.generatedBy,
    data.generatedDate,
    data.status,
    data.category,
    data.totalRecords,
    data.fileSize,
    data.downloadUrl,
    data.expiryDate,
    data.updatedAt,
    data.createdAt,
  ];
};

const ExportReportsDataToExcel = (filtered: string, data: any[]): void => {
  const dynamicData = [
    EXCEL_HEADERS,
    ...data.map((row) => formatRowData(row, filtered === "filtered")),
  ];

  const ws: XLSX.WorkSheet = XLSX.utils.aoa_to_sheet(dynamicData);
  const wb: XLSX.WorkBook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Sheet 1");
  XLSX.writeFile(wb, "Reports.xlsx", { bookSST: true });
};

export default ExportReportsDataToExcel;

// Create a worksheet
